apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener
resources:
  - ../../base
  - ingress.yaml
images:
  - name: REPLACE with ECR/image
    newName: xxxx.dkr.ecr.us-east-1.amazonaws.com/url-shortener-service
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: shortener
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: 
          - name: ecr-creds
