name: Build & Push
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable:
    uses: bar-private-org/reusable-workflows/.github/workflows/ecr-build-push.yml@main
    with:
      ecr_repo: "url-shortener-service"
      aws_region: ${{vars.AWS_REGION}}
    secrets: inherit
